### ISSUE TITLE
Update the selected input value when the options changed

### ISSUE THREAD

**Issue by wannfq** [raycharius/slack-block-builder#115]
**Is your feature request related to a problem? Please describe.**
I cannot reset the value of the select input that uses external data for options when the options data were updated.
This could be a **bug** rather than **enhancement**, still torn on that.

**Describe the solution you'd like**
Reset the selected input value when the selected item in the options has been removed.

**Describe alternatives you've considered**
No alternative so far. Any suggestions are welcomed

**Additional context**

Initial options contain `Engineer` and it was selected
https://user-images.githubusercontent.com/26282828/220018817-f0cca6d7-c934-4f8c-a6bd-345f3f40ab34.mov

All options were removed and the `Engineer` was still selected
https://user-images.githubusercontent.com/26282828/220019485-edc4bbf3-c368-4647-8974-309e626464fb.mov

Upon debugging, when the form was submitted the value for the `Role` field was still `Engineer`

**Comment by raycharius** [comment]
Hi there, and sorry for the late response! Unfortunately, I'm not sure how the library could solve that particular issue, since its job is to provide an abstraction over the API. This sounds like it might best redirected to the folks at Slack. But if there is way for you to sync the two, the best way would be to track those changes and use the Update View endpoint preemptively and remove that selected value when you know that an option is no longer there.

Cheers!
