### ISSUE TITLE
Ephemeral Message in DirectMessage not working 

### ISSUE THREAD

**Issue by choongyouqi** [raycharius/slack-block-builder#59]
**Describe the Bug**

The goal is able to respond/say in DM publically(seen to all parties) when using slash command in direct message.

**To Reproduce**

the method below is not working:
```
await respond(Message()
        .blocks(Blocks.Section().text("Team Members"))
        .attachments(attachments)
        .ephemeral(false)
        .buildToObject()
```

I have to resort to the manual way
```
 await respond({
     "response_type": "in_channel",
     "blocks": BlockCollection(Blocks.Section().text("Team Members")),
     "attachments": AttachmentCollection(attachments),
 })
```

**Expected Behavior**
- to provide a way to add `response_type` in lib level

**Comment by raycharius** [comment]
Hi! There are two methods available that can set the `response_type`: 

`MessageBuilder.ephemeral()`
`MessageBuilder.inChannel()`

Since not all message payloads require this parameter, passing in `false` to `MessageBuilder.ephemeral()` does not set the response type to `in_channel`, so the best way to do that is to call `MessageBuilder.inChannel()`

Let me know it that solves this for you!
