### ISSUE TITLE
Using excludeBotUsers() on conversation select element does not confrom to Slack API

### ISSUE THREAD

**Issue by ajkitson** [raycharius/slack-block-builder#74]
**First**
This lib is terrific -- it's really sped up iterating with block kit and the it's very intuitive to use. Really well done!

Happy to do a PR, but I haven't oriented to the internals of the lib yet. Let me know if that'd be helpful!

**Describe the Bug**
When I use `excludeBotUsers` on a conversation-select element, Slack rejects the output: 
```js
{
  code: 'slack_webapi_platform_error',
  data: {
    ok: false,
    error: 'invalid_arguments',
    response_metadata: {
        messages: [
          '[ERROR] failed to match all allowed schemas [json-pointer:/view]',
          '[ERROR] invalid additional property: exclude_bot_users [json-pointer:/view/blocks/0/element]'
        ]
    ...
}
```
The issue appears to be that `exclude_bot_users` is included twice. Once in `filters` where it belongs and once on `element` where it does not:
```js
    "blocks": [
        {
            "block_id": "my-channel",
            ...
            "element": {
                "action_id": "abc-channel-select",
                "exclude_bot_users": true, //  <---- THIS IS THE ISSUE
                "type": "conversations_select",
                "filter": {
                    "exclude_bot_users": true
                }
            },
    ],
}
``` 
If I delete `exclude_bot_users` from `element` before sending it to Slack, it works just fine.

**To Reproduce**
Using Bolt, display this modal in response to a shortcut:
```js
async function showModal({ ack, shortcut, client }) {
  await ack();
  const myModal = Modal({ 
    title: 'My Modal',
    callbackId: 'my-modal',
   submit: 'Submit'
  })
  .blocks(
    Blocks.Input()
      .blockId('my-channel')
      .label('Choose channel')
      .element(
        Elements.ConversationSelect({
          actionId: 'abc-channel-select'
        })
        .excludeBotUsers() // works when I comment this out
      )      
  )
  .buildToObject();

  await client.views.open({
    trigger_id: shortcut.trigger_id,
    view: myModal,
  });
}
```

**Expected Behavior**
The output conforms to the Slack API

**Comment by raycharius** [comment]
Hi @ajkitson! Thanks for sending this over! I could get to this over the weekend or early next week, but feel free to send over a PR. 

I definitely need to get to documenting the compositional approach to the library's source code, but it looks like the issue is probably [here](https://github.com/raycharius/slack-block-builder/blob/main/src/lib/slack-dto.ts). The resulting DTOs are created dynamically by mapping the builder properties (camel case) to the API-supported properties (snake case). 

I imagine removing along with the other filter related properties in `Param` would fix the issue. Let me know if you want to take a look, and if you don't have the time, I'll get to it in the next couple of days.

Cheers!

**Comment by raycharius** [comment]
Also, I need to get around to adding contribution guidelines and the right Git hooks, but you might want to take a look at [this](https://github.com/raycharius/slack-block-builder/blob/main/.github/workflows/ci-build.yml) for commit convention for this repo

**Comment by ajkitson** [comment]
Cool. That looks pretty straightforward. I've got some time this afternoon to try it out and put together a PR.
