### ISSUE TITLE
Expose .build() on Element and Block builders

### ISSUE THREAD

**Issue by itsjackgardner** [raycharius/slack-block-builder#78]
**Is your feature request related to a problem? Please describe.**
For our specific use case `slack-block-builder` works very well for building block collections that we pass to the API. However, we also want to respond to Slack actions on our messages by editing the original message (e.g. reading in the current blocks object of a message and replacing certain sections).

**Describe the solution you'd like**
It would be ideal if the block and element builders types exposed the `.build()` function that is used under the hood by `BlockCollection` so that we could build a single element.

**Describe alternatives you've considered**
Currently I need to do something like:
```
const actionsObject = BlockCollection(Blocks.Actions().elements(element)).pop() as ActionsBlock | undefined;
const elementObject = actionsObject?.elements.pop();
return elementObject;
```
Where I'm casting to types exposed by `@slack/bolt` because `SlackBlockDto` doesn't have the elements field even when you can assert the type of the block.
I'd love for this to be simplified to just `element.build()` so we don't need to mess around with the `BlockCollection` and types.

**Comment by raycharius** [comment]
Hi @itsjackgardner, thanks for this issue and sorry for the delayed response. This definitely has given me some things to think about!

I'd love to hear more about your use case! With the apps that I've created, I always build out messages and modals, even ones that have dynamic content, from scratch. So a message where content is modified depending on, say, the state of an entity, is always built from scratch and the logic on how it should be built is typically encapsulated in the function responsible for creating the UI. So I'd love to know more about why your particular app needs to access and modify existing messages and modals directly – first off, just curious and love any chance to find out more about how other developers are building things, and secondly, it may point us to a great solution!

On type casting, that's a great point to bring up. Currently, the library has a couple of general DTO classes that are built dynamically to make it a bit more maintainable, but I plan on moving back to a single DTO class for each builder class in version three. And I also plan to go ahead and use Slack's own types once that happens.

I'd love to hear more about your case, and from there work on a solution. In the meantime, I am happy to remove the `internal` comments from the `build()` methods so that TS includes them in the type definitions. Although it will still currently return a general `SlackBlockDto`, it would still keep you from having to use the surfaces or the collection functions.

**Comment by raycharius** [comment]
Hi there, closing this for now. I will expose the methods in v.3, when they will provide more value, as each will return a specific type. Currently they all return a generalized DTO.

Thanks! And keep and eye out!

**Comment by raycharius** [comment]
Hi @itsjackgardner, had a few other requests for similar feature, and as a viable option, since exposing the `build()` method can create side effects, I went ahead and added `buildBlock()` and `buildBlocks()` functions to the library for this purpose. It's available in the latest release, enjoy!
