### ISSUE TITLE
getBlock()

### ISSUE THREAD

**Issue by odedhb** [raycharius/slack-block-builder#98]
Same as `.getBlocks()` for a surface, can we `getBlock()` for A single block?

I'm using:
```
function toBlock(block) {
    return HomeTab().blocks([block]).getBlocks()[0];
}
```

**Comment by raycharius** [comment]
Hi @odedhb, thanks for sending this over! There have been some similar requests, asking us to expose the `build()` method, but since that's more of an edge case and can create side effects, I went ahead and added `buildBlock()` and `buildBlocks()` functions to the library for this purpose. It's available in the latest release, enjoy!
